# Generated by Django 6.0.6 on 2026-07-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_fbv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
