services:
  - type: web
    name: djangocrud
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangocrud.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
